### PR TITLE
Refactoring changepreferences 

### PR DESCRIPTION
**Pull request by FrankDomburg**
Makes a singleton out of sharedpreferences making the Activity (slightly) cleaner

Prepares for easy addition and re-used of additional preferences

### CODE REVIEW

**Comment by karino2** [comment]
Do you plan to add another preference?
I think this PR is OK, but I want to know the motivation.

**Comment by FrankDomburg** [comment]
I have no firm ideas just yet.

However, I am thinking about some of the stuff I read on reddit – like being able to add tags. SharedPreferences could then be used to hold a list of them.

Also, if there will be PDF/PNG switches, those would probably become preferences, too.

Finally, but maybe the most important, location of template files, once the background is configurable.

So, I guess they are around the corner, though not fully defined yet.



Van: karino2 ***@***.***>
Datum: zaterdag, 26 maart 2022 om 11:37
Aan: karino2/PngNote ***@***.***>
CC: FrankDomburg ***@***.***>, Author ***@***.***>
Onderwerp: Re: [karino2/PngNote] Refactoring changepreferences (PR #6)

Do you plan to add another preference?
I think this PR is OK, but I want to know the motivation.

**Comment by karino2** [comment]
OK. I accept.

**Comment by FrankDomburg** [comment]
Karino2, hadn't tested it fully. Now the App refuses to start because PrefManager.init(applicationcontext) generates an exception :-(

Not sure why, only thing I could Google that the application name in the manifest should not be empty - though I wonder why.

Do you have any ideas?

**Comment by karino2** [comment]
Oh, really? I'll try.

**Comment by FrankDomburg** [comment]
Currently suspecting it is caused by the direct link between the ui and the
uri stored in sharedprefs.

In that case, when adding a viewmodel, is should resolve as the first state
would be something like not specified.

Op za 26 mrt. 2022 15:26 schreef karino2 ***@***.***>:

**Comment by karino2** [comment]
I understand the reason. I'll fix first.

**Comment by karino2** [comment]
It is because uri is initialized as a field initializer, but field initialization occurs before you set preferences.
I feel this code is more fragile than the previous one.
It is not statically ensured that preferences are set before using it, but the previous code was statically ensured that all fields are initialized before using it.

But I'll wait to see what you'll add to this preference.
If it's worth this fragility, it's OK. If not, then we can revert at that time.

**Comment by FrankDomburg** [comment]
I think in this case uri = null means not initialized, but for the
application  also not entered? Basically different states.

But it works now.

I am proceeding to add a viewmodel to booklistactivity and possibly a
domain layer for the file access.

Then it should be good to go for the bookactivity and being able to select
different backgrounds.

Not sure if jetcompose for preview is worth it.

What do you think?

Also, did you look at a Navigator? I saw your app has multiple activities,
where navigator seems to prefer fragments.

Op za 26 mrt. 2022 15:46 schreef karino2 ***@***.***>:

**Pull request merged**
