### PR TITLE
Introduce hilt

### PR DESCRIPTION
**Pull request by FrankDomburg**

### CODE REVIEW

**Comment by FrankDomburg** [comment]
When moving to MVVM there will be a number of dependencies, which is a lot of boiler plate, so introducing Google's recommended solution.

Moving to MVVM, will make a cleaner implementation much easier.

**Comment by karino2** [comment]
I'm a little confusing.
Why do you introduce another structure change before adding anything to Pref？
I thought you introduced PrefManager because you need this change to add something you want.

And you made many changes without adding any features this time too.
I can't judge whether this change is necessary or not without adding anything.
Why do you want to add hilt, update minSDK, and introduce MVVM?

If it is just because Google says it is good architecture, I disagree.
And the purpose of changing architecture is changing architecture; then, I recommend you fork this project and develop your own.
I do not yet understand what you want to do for PDF-related topics.
But maybe it seems like a different app.

**Comment by FrankDomburg** [comment]
Was updating the stuff needed to work with flexible background pngs (as the first feature)

But then got confused, because a lot of file stuff was happening mixed with image stuff.

Also noticed that livedata of the document list, at some point goes stale and the application crashes.

Since viewmodel ensures that the data is there, when the screen is up. And a good formed data layer will make it easier to do background selection, it seemed that this makes sense in order to move forward.

**Comment by FrankDomburg** [comment]
Also, basically the prefmanager is the same, just using the hilt stuff. Still a singleton, and still has the same basic role. Implemented like this, it just proves the hilt glue works and holds.

**Comment by karino2** [comment]
I couldn't understand why we needed so much change just supporting more flexible background image settings.

I recommend you fork this project and develop your own app.
You seem to want to go too further to merge this repository.
I think it's a nice thing to develop many apps for BOOX by many developers.

**Comment by FrankDomburg** [comment]
Because 2 know more than 1, was my hope.

Don't know much about app publishing or compose.

Liked the idea of building together.

Op do 31 mrt. 2022 13:54 schreef karino2 ***@***.***>:

**Comment by karino2** [comment]
I think persuading me is a waste of time.
You can develop as you want with that time.

Anyway, I couldn't understand the necessity of this PR, as I said.
Reject this PR and further architectural change without adding any features.

**Comment by FrankDomburg** [comment]
Wasn't persuading you at all, just giving you an idea of what I wanted /
hoped to achieve.

Had hoped that we could make something Onyx just doesn't seem to want to
make.

Clear you don't. Too bad. Read your initial post on reddit differently.

Won't be doing any pull requests any more. At all.

Do see your comment as an ok to use your code as basis for whatever I do
next.

Op do 31 mrt. 2022 14:58 schreef karino2 ***@***.***>:

**Comment by karino2** [comment]
I appreciate your feedback.
But really, you seem to want to create a different app.
Forking an app is not a bad thing at all.

Please use different app-id and launcher icon for your app when forking.

**Comment by FrankDomburg** [comment]
I really didn't - and to me, this just plain sucks. But it's life, and I'll live.

Not sure what app-id is. Launcher, I will look at.

Requested the fork to be detached.

**Pull request closed without merging**
