### PR TITLE
Updated to latest gradle versions and JAVA 11

### PR DESCRIPTION
**Pull request by FrankDomburg**
Updated to JAVA 11 via JAVA 1.8

Application now builds on my computer - assuming these are non breaking changes. Did not change any of the other dependencies. Not sure yet of how to test this, so assuming Android Studio did its work correctly (and since I touched no functionality, it should work, right?)

### CODE REVIEW

**Comment by karino2** [comment]
Thank you for PR.
What API do you think we need min SDK 29？

**Comment by karino2** [comment]
I think what you are insisting in this PR top comment (Updated to latest gradle versions and JAVA 11) and density calculation is different topic.
Former case, I want to merge after I check in my device in this weekend.

For later, I don't understand the motivation for splitting code yet.
If you do this modification only because google says it's deprecated, I don't want to split code because I only have Note3 device and I can't check older devices, which means I can only test one branch of code in device.
Making test harder seems not the right path for the hobby personal project like PngNote.

Anyway, if you want to merge later one too, could you separate PR?

**Comment by FrankDomburg** [comment]
Not sure yet, hence I put out a question on reddit, might even be one level
higher, but it seems not all your listed devices are on the same android
(yet), so thought this was safe.

Frank

Op vr 25 mrt. 2022 14:40 schreef karino2 ***@***.***>:

**Comment by FrankDomburg** [comment]
Hi,

Not sure how to discuss this on github. And also not so proficient at
splitting PRs. (Have one coming up to clean out sharedpreferences)

Wrt density - i am supposing/hoping onyx will maintain the android version.
Density calculation works at higher android versions, just not sure on a
note air. This will make the application last longer :)

So hope you reconsider.

Wrt hobby project. I think I might have found a way to expand this into
PDFs, in a cool (and free!) way.

Using these PRs to come to grip with your code base and preparing the
structure to add that.

That would be a 2 step process, slightly ambitious for me, as kotlin is
rusty.

Zero, would like to enable custom backgrounds for the png background

First, I would like to be able to make the background into a pdf and be
able to render that with writing to a new pdf.

Second, I would like to make a picker to be able to insert a user-selected
page from a template pdf into the note. And then be able to export that.

Something like that, at least, my thinking is evolving.

Regards
Frank

Op vr 25 mrt. 2022 15:34 schreef karino2 ***@***.***>:

**Comment by karino2** [comment]
PR splitting is git basics...But OK.

Could you give me more information on why you want to add Android 11 dependent code?
For example
- There are some problems with your device in older code
- You plan to write some Android 11-depend code in your fork version, and it's convenient to be Android11 compliant as an upstream

The reason, like the later one, is also appreciated.
I want to change this part in the future to show more books on one top page (4x4, maybe), so if possible, I don't want to add code that I can't test.
If you just think the newer API would last longer, I'm sure the BOOX pen-SDK update will stop much earlier than drop this API, so I disagree.

So if you do not give me other reasons, I will reject the last commit and merge the former two only.

If Note Air is Android 10, I think min SDK to Android 10 is acceptable.
But my Note3 seems Android 10. We need a good reason if you want to add Android 11 specific code!

**Comment by karino2** [comment]
OK, continue on #3 PR.
I'll merge this PR first.

**Comment by karino2** [comment]
This PR is merged by #4.

**Pull request closed without merging**
